name = "e2e_test"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_time = ">= 1.8.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
skir_client = ">= 1.0.1 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.9.0 and < 2.0.0"
