import { type CodeGenerator, type Module, type RecordKey, type RecordLocation, convertCase } from "skir-internal";
import { z } from "zod";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

class GleamCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-gleam-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      outputFiles.push({
        path: modulePathToGleamPath(module.path),
        code: new GleamSourceFileGenerator(module).generate(),
      });
    }
    return { files: outputFiles };
  }
}

// Generates the code for one Gleam source file.
class GleamSourceFileGenerator {
  private readonly lines: string[] = [];

  constructor(private readonly inModule: Module) {}

  generate(): string {
    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.push(
      `//  ______                        _               _  _  _
//  |  _  \\                      | |             | |(_)| |
//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_
//  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _\` || || __|
//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_
//  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|
//
// Generated by skir-gleam-gen
// Home: https://github.com/gepheum/skir-gleam-gen
//
// Do not edit this file manually.
`,
    );

    const { records } = this.inModule;

    for (const recordLocation of records) {
      const { record } = recordLocation;
      // Only generate top-level records (not nested ones).
      if (recordLocation.recordAncestors.length > 1) {
        continue;
      }
      const typeName = convertCase(record.name.text, "UpperCamel");
      this.push(`pub type ${typeName} {}`);
      this.push("");
    }

    return this.lines.join("\n");
  }

  private push(...lines: string[]): void {
    for (const line of lines) {
      this.lines.push(line);
    }
  }
}

/**
 * Converts a Skir module path to the path of the corresponding Gleam file.
 *
 * Examples:
 *   "user.skir"                              → "skirout/user.gleam"
 *   "@gepheum/skir-golden-tests/goldens.skir" → "skirout/gepheum/skir_golden_tests/goldens.gleam"
 */
function modulePathToGleamPath(modulePath: string): string {
  return (
    modulePath
      // Strip leading "@"
      .replace(/^@/, "")
      // Replace hyphens with underscores (Gleam module names use snake_case)
      .replace(/-/g, "_")
      // Replace .skir extension with .gleam
      .replace(/\.skir$/, ".gleam")
  );
}

export default new GleamCodeGenerator();
